/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package quanlychothuexe;

import com.sun.tools.javac.Main;
import java.awt.FlowLayout;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.io.File;
import java.io.IOException;
import java.lang.System.Logger;
import java.lang.System.Logger.Level;
import java.util.HashSet;
import java.util.Set;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author ThanhTin
 */
public class MenuForm extends javax.swing.JFrame {
  
private JPanel childPanel; 
    /**
     * Creates new form MenuForm
     */
    public MenuForm() {
        initComponents();
//        this.setUndecorated(true);
//        this.setAlwaysOnTop(true);
//        this.setResizable(true);
////        this.setVisible(true);
//        Toolkit tk = Toolkit.getDefaultToolkit();
//        int xsize = (int) tk.getScreenSize().getWidth();
//        int ysize = (int) tk.getScreenSize().getHeight();
//        this.setSize(xsize,ysize);
//        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jToolBar1 = new javax.swing.JToolBar();
        btnhome = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        jSeparator3 = new javax.swing.JToolBar.Separator();
        btncar = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        btncustomer = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JToolBar.Separator();
        btnstaff = new javax.swing.JButton();
        jSeparator5 = new javax.swing.JToolBar.Separator();
        btnbill = new javax.swing.JButton();
        jSeparator6 = new javax.swing.JToolBar.Separator();
        btnstats = new javax.swing.JButton();
        jSeparator7 = new javax.swing.JToolBar.Separator();
        btnpay = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        panelmenu = new javax.swing.JPanel();
        lblogo = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        btnAbout = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Hinh/Picture1.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 162, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jMenu3.setText("File");
        jMenuBar2.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar2.add(jMenu4);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jToolBar1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jToolBar1.setRollover(true);

        btnhome.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnhome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Hinh/Home.png"))); // NOI18N
        btnhome.setText("HOME");
        btnhome.setFocusable(false);
        btnhome.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnhome.setMargin(new java.awt.Insets(6, 18, 6, 18));
        btnhome.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnhome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnhomeMouseClicked(evt);
            }
        });
        btnhome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhomeActionPerformed(evt);
            }
        });
        jToolBar1.add(btnhome);
        jToolBar1.add(jSeparator1);
        jToolBar1.add(jSeparator3);

        btncar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btncar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Hinh/xe.png"))); // NOI18N
        btncar.setText("CAR");
        btncar.setFocusable(false);
        btncar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btncar.setMargin(new java.awt.Insets(6, 18, 6, 18));
        btncar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btncar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncarActionPerformed(evt);
            }
        });
        jToolBar1.add(btncar);
        jToolBar1.add(jSeparator2);

        btncustomer.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btncustomer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Hinh/Users.png"))); // NOI18N
        btncustomer.setText("CUSTOMER");
        btncustomer.setFocusable(false);
        btncustomer.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btncustomer.setMargin(new java.awt.Insets(6, 18, 6, 18));
        btncustomer.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btncustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncustomerActionPerformed(evt);
            }
        });
        jToolBar1.add(btncustomer);
        jToolBar1.add(jSeparator4);

        btnstaff.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnstaff.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Hinh/User.png"))); // NOI18N
        btnstaff.setText("STAFF");
        btnstaff.setFocusable(false);
        btnstaff.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnstaff.setMargin(new java.awt.Insets(6, 18, 6, 18));
        btnstaff.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnstaff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnstaffActionPerformed(evt);
            }
        });
        jToolBar1.add(btnstaff);
        jToolBar1.add(jSeparator5);

        btnbill.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnbill.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Hinh/Notes.png"))); // NOI18N
        btnbill.setText("BILL");
        btnbill.setFocusable(false);
        btnbill.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnbill.setMargin(new java.awt.Insets(6, 18, 6, 18));
        btnbill.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnbill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbillActionPerformed(evt);
            }
        });
        jToolBar1.add(btnbill);
        jToolBar1.add(jSeparator6);

        btnstats.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnstats.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Hinh/Statistics.png"))); // NOI18N
        btnstats.setText("STATS");
        btnstats.setFocusable(false);
        btnstats.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnstats.setMargin(new java.awt.Insets(6, 18, 6, 18));
        btnstats.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnstats.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnstatsActionPerformed(evt);
            }
        });
        jToolBar1.add(btnstats);
        jToolBar1.add(jSeparator7);

        btnpay.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnpay.setForeground(new java.awt.Color(255, 0, 51));
        btnpay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Hinh/Price list.png"))); // NOI18N
        btnpay.setText("PAYMENT");
        btnpay.setFocusable(false);
        btnpay.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnpay.setMargin(new java.awt.Insets(6, 18, 6, 18));
        btnpay.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnpay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpayActionPerformed(evt);
            }
        });
        jToolBar1.add(btnpay);

        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setPreferredSize(new java.awt.Dimension(50, 100));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        panelmenu.setBackground(new java.awt.Color(255, 255, 255));
        panelmenu.setMinimumSize(new java.awt.Dimension(673, 579));
        panelmenu.setPreferredSize(new java.awt.Dimension(673, 579));
        panelmenu.setLayout(new java.awt.BorderLayout());

        lblogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Hinh/Picture1.jpg"))); // NOI18N
        lblogo.setPreferredSize(new java.awt.Dimension(673, 579));
        lblogo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        panelmenu.add(lblogo, java.awt.BorderLayout.CENTER);

        jMenu1.setText("File");

        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Hinh/Unknown person.png"))); // NOI18N
        jMenuItem1.setMnemonic('\u0110');
        jMenuItem1.setText("User Sign In");
        jMenu1.add(jMenuItem1);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Hinh/Exit.png"))); // NOI18N
        jMenuItem2.setMnemonic('T');
        jMenuItem2.setText("Exit");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        btnAbout.setText("About");
        btnAbout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAboutMouseClicked(evt);
            }
        });
        btnAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAboutActionPerformed(evt);
            }
        });
        jMenuBar1.add(btnAbout);

        jMenu5.setText("Help");
        jMenu5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu5MouseClicked(evt);
            }
        });
        jMenu5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu5ActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1300, Short.MAX_VALUE)
            .addComponent(panelmenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1300, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(panelmenu, javax.swing.GroupLayout.PREFERRED_SIZE, 616, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnhomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhomeActionPerformed
    childPanel = new trangchu();
    panelmenu.removeAll();
    panelmenu.add(childPanel);
    panelmenu.validate();

    }//GEN-LAST:event_btnhomeActionPerformed
private void showPanel(JPanel panel){
//    childPanel = panel;
//    panelmenu.removeAll();
//    panelmenu.add(childPanel);
//    panelmenu.validate();
    
}

    private void btncustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncustomerActionPerformed

//   lblogo.setVisible(false);
//   showPanel(new panel1());
    childPanel = new khachhangform1();
    panelmenu.removeAll();
    panelmenu.add(childPanel);
    panelmenu.validate();
    }//GEN-LAST:event_btncustomerActionPerformed

    private void btnbillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbillActionPerformed
    childPanel = new HoaDonForm1();
    panelmenu.removeAll();
    panelmenu.add(childPanel);
    panelmenu.validate();
    }//GEN-LAST:event_btnbillActionPerformed

    private void btnhomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnhomeMouseClicked
         
    }//GEN-LAST:event_btnhomeMouseClicked

    private void btnstaffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnstaffActionPerformed
    childPanel = new NhanVienForm1();
    panelmenu.removeAll();
    panelmenu.add(childPanel);
    panelmenu.validate();
    }//GEN-LAST:event_btnstaffActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
//        System.exit(0);
//    SignForm SignForm = new SignForm();
//    SignForm.setDefaultCloseOperation(MenuForm.HIDE_ON_CLOSE);
    
//    this.dispatchEvent(new WindowEvent(this, WindowEvent.WINDOW_CLOSING));
    new SignForm().setVisible(true);
    dispose();       
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void btnAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAboutActionPerformed
   
    }//GEN-LAST:event_btnAboutActionPerformed

    private void btnAboutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAboutMouseClicked
    childPanel = new aboutForm();
    panelmenu.removeAll();
    panelmenu.add(childPanel);
    panelmenu.validate();
    }//GEN-LAST:event_btnAboutMouseClicked

    private void btncarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncarActionPerformed
    childPanel = new XeForm1();
    panelmenu.removeAll();
    panelmenu.add(childPanel);
    panelmenu.validate();
    }//GEN-LAST:event_btncarActionPerformed

    private void btnpayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpayActionPerformed
    childPanel = new ThanhToanForm();
    panelmenu.removeAll();
    panelmenu.add(childPanel);
    panelmenu.validate();
    }//GEN-LAST:event_btnpayActionPerformed

    private void btnstatsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnstatsActionPerformed
    childPanel = new ThongKeForm1();
    panelmenu.removeAll();
    panelmenu.add(childPanel);
    panelmenu.validate();
    }//GEN-LAST:event_btnstatsActionPerformed

    private void jMenu5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu5ActionPerformed
//         try {
//            java.awt.Desktop.getDesktop().open(new java.io.File("C:\\Users\\ThanhTin\\Desktop\\Help\\help.chm"));
//        } catch (IOException ex) {
//            System.out.print("Khong the mo duoc file Help!");
//        }
    }//GEN-LAST:event_jMenu5ActionPerformed

    private void jMenu5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu5MouseClicked
        try {
            java.awt.Desktop.getDesktop().open(new java.io.File("D:\\QuanLyChoThueXe\\src\\Help\\help.chm"));
        } catch (IOException ex) {
            System.out.print("Khong the mo duoc file Help!");
        }
    }//GEN-LAST:event_jMenu5MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                 
                new MenuForm().setVisible(true);
//                 frame.setExtendedState(JFrame.MAXIMIZED_BOTH); 
//frame.setUndecorated(true);
//frame.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu btnAbout;
    private javax.swing.JButton btnbill;
    private javax.swing.JButton btncar;
    private javax.swing.JButton btncustomer;
    private javax.swing.JButton btnhome;
    private javax.swing.JButton btnpay;
    private javax.swing.JButton btnstaff;
    private javax.swing.JButton btnstats;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JToolBar.Separator jSeparator3;
    private javax.swing.JToolBar.Separator jSeparator4;
    private javax.swing.JToolBar.Separator jSeparator5;
    private javax.swing.JToolBar.Separator jSeparator6;
    private javax.swing.JToolBar.Separator jSeparator7;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel lblogo;
    private javax.swing.JPanel panelmenu;
    // End of variables declaration//GEN-END:variables
}
