/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package quanlychothuexe;
import javax.swing.table.DefaultTableModel;
import java.util.*;
import javax.swing.table.DefaultTableModel;
import java.sql.*;
import java.sql.Connection;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import java.sql.PreparedStatement;
import java.text.DecimalFormat;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author ThanhTin
 */
public class ThanhToanForm extends javax.swing.JPanel {
DefaultTableModel tbn =new DefaultTableModel();
    /**
     * Creates new form ThanhToanForm
     */
    public ThanhToanForm() {
        initComponents();
        loadData();
//        Tong();
    }
public void loadData(){
    try{
        Connect a=new Connect();
        Connection conn = a.getConnection();
        int number;
        Vector row,column ;
         column = new Vector();
        
        Statement st =conn.createStatement();
//         ResultSet rs=st.executeQuery("select * from tbXe");
        ResultSet rs=st.executeQuery("Select tbXe.MaHD,tbNhanVien.MaNV,TenNV,tbKhachhang.MaKH,TenKH,tbXe.MaXe,TenXe,ngaythue,ngaytra,thue,GiaXe, convert(int,DATEDIFF(day,Ngaythue,Ngaytra))*GiaXe as \"Số ngày * giá xe\",trangthaihoadon\n" +
"from tbXe,tbNhanVien,tbHoaDon,tbkhachhang \n" +
"where tbNhanVien.MaNV=tbHoaDon.MaNV and tbHoaDon.MaKH=tbkhachhang.MaKH and tbXe.MaHD=tbHoaDon.MaHD ");
ResultSetMetaData  metadata = rs.getMetaData();
number = metadata.getColumnCount();
for(int i=1;i<=number;i++){
 column.add(metadata.getColumnName(i));
}
tbn.setColumnIdentifiers(column);
while(rs.next()){
row =new Vector();
for(int i=1;i<=number;i++){
    row.addElement(rs.getString(i));
}
tbn.addRow(row);
tbthanhtoan.setModel(tbn);
}
 tbthanhtoan.getSelectionModel().addListSelectionListener(new ListSelectionListener(){
               @Override
               public void valueChanged(ListSelectionEvent e) {
                   if(tbthanhtoan.getSelectedRow()>=0){
                       txttimkiem.setText(tbthanhtoan.getValueAt(tbthanhtoan.getSelectedRow(), 0)+"");
//                       txtmanv.setText(tbthanhtoan.getValueAt(tbthanhtoan.getSelectedRow(), 1)+"");
//                       txttennv.setText(tbthanhtoan.getValueAt(tbthanhtoan.getSelectedRow(),2)+"");
//                       txtmakh.setText(tbthanhtoan.getValueAt(tbthanhtoan.getSelectedRow(), 3)+"");
//                       txttenkh.setText(tbthanhtoan.getValueAt(tbthanhtoan.getSelectedRow(), 4)+"");
//                       txtmaxe.setText(tbthanhtoan.getValueAt(tbthanhtoan.getSelectedRow(), 5)+"");
//                       txttenxe.setText(tbthanhtoan.getValueAt(tbthanhtoan.getSelectedRow(), 6)+"");
//                       txtngaynhan.setText(tbthanhtoan.getValueAt(tbthanhtoan.getSelectedRow(), 7)+"");
//                       txtngaytra.setText(tbthanhtoan.getValueAt(tbthanhtoan.getSelectedRow(), 8)+"");
//                       txtthue.setText(tbthanhtoan.getValueAt(tbthanhtoan.getSelectedRow(), 9)+"");
//                       txtgia.setText(tbthanhtoan.getValueAt(tbthanhtoan.getSelectedRow(), 10)+"");
//                       txtgiathuenhansongay.setText(tbthanhtoan.getValueAt(tbthanhtoan.getSelectedRow(), 11)+"");
                     
                   }
               }
 });
    
    }catch(Exception ex){
        System.out.println(ex.toString());
    }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbthanhtoan = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        btnthanhtoan = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        btnxoa = new javax.swing.JButton();
        btnsua = new javax.swing.JButton();
        lbtongtien = new javax.swing.JLabel();
        txttimkiem = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        btnchitiethoadon = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 51));
        jLabel1.setText("THANH TOÁN");

        tbthanhtoan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbthanhtoan);

        jLabel2.setText("Mã hóa đơn:");

        btnthanhtoan.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnthanhtoan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Hinh/Accept.png"))); // NOI18N
        btnthanhtoan.setText("THANH TOÁN");
        btnthanhtoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnthanhtoanActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 51));
        jLabel3.setText("TỔNG TIỀN:");

        btnxoa.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnxoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Hinh/Delete.png"))); // NOI18N
        btnxoa.setText("Xóa");
        btnxoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnxoaActionPerformed(evt);
            }
        });

        btnsua.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnsua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Hinh/Notes.png"))); // NOI18N
        btnsua.setText("Sửa");
        btnsua.setActionCommand("Cập nhật");
        btnsua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsuaActionPerformed(evt);
            }
        });

        lbtongtien.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lbtongtien.setForeground(new java.awt.Color(255, 0, 51));

        txttimkiem.setText("Tìm kiếm");
        txttimkiem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txttimkiemMouseClicked(evt);
            }
        });
        txttimkiem.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txttimkiemKeyReleased(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel13.setBackground(new java.awt.Color(255, 255, 255));
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Hinh/hand-giving-money-another-isolated-260nw-166449140.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(255, Short.MAX_VALUE)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 753, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(136, 136, 136))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        btnchitiethoadon.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnchitiethoadon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Hinh/Documents.png"))); // NOI18N
        btnchitiethoadon.setText("Chi tiết hóa đơn");
        btnchitiethoadon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnchitiethoadonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator3)
                            .addComponent(jSeparator4)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lbtongtien)
                                .addGap(40, 40, 40))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(18, 18, 18)
                                        .addComponent(txttimkiem))
                                    .addComponent(jSeparator1)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1260, Short.MAX_VALUE)
                                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 1258, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addComponent(btnxoa)
                        .addGap(18, 18, 18)
                        .addComponent(btnsua)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnchitiethoadon)
                        .addGap(26, 26, 26)
                        .addComponent(btnthanhtoan))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(60, 60, 60)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(554, 554, 554)
                                .addComponent(jLabel1)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txttimkiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lbtongtien))
                .addGap(12, 12, 12)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnthanhtoan)
                    .addComponent(btnsua)
                    .addComponent(btnxoa)
                    .addComponent(btnchitiethoadon))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnxoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnxoaActionPerformed
        try{
            Connect a=new Connect();
            Connection conn=a.getConnection();
            PreparedStatement ps =conn.prepareStatement("Delete tbHoaDon where MaHD=?");
            ps.setString(1,tbthanhtoan.getValueAt(tbthanhtoan.getSelectedRow(),0).toString());
            if(JOptionPane.showConfirmDialog(this, "bạn có chắc muốn xóa","Confirm",
                JOptionPane.YES_NO_OPTION)==JOptionPane.YES_OPTION){
            ps.executeUpdate();
            tbn.setRowCount(0);
            loadData();

        }
        }catch(Exception ex)
        {
            System.out.println(ex.toString());
        }
    }//GEN-LAST:event_btnxoaActionPerformed

    private void btnsuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsuaActionPerformed
//        try{
//            Connect a =new Connect();
//            Connection conn=txtmahdtion();
//            PreparedStatement ps =conn.prepareStatement("update tbhoadon set maxe=?,makh=?,manv=?,maloaixe=?,thue=?,PTTT=? where mahd=? ");
//            ps.setString(7,txtmahd.getText());
//            ps.setString(1,txtmaxe.getText());
//            ps.setString(2,txtmakh.getText());
//            ps.setString(3,txtnhanvien.getText());
//            ps.setString(4,txtmaloaixe.getText());
//            ps.setString(5,txtthue.getText());
//            ps.setString(6,txtptt.getText());
//            tbn.setRowCount(0);
//            ps.executeUpdate();
//            loadData();
//            JOptionPane.showMessageDialog(this, "Cập nhật thành công");
//        }catch(Exception ex){
//            System.out.println(ex.toString());
//
//        }
    }//GEN-LAST:event_btnsuaActionPerformed

    private void txttimkiemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txttimkiemMouseClicked
        txttimkiem.setText("");
    }//GEN-LAST:event_txttimkiemMouseClicked
//      private void Tong(){
//    DecimalFormat x = new DecimalFormat("###,###,###");
//    int Tong = 0;
//    for(int i=0;i<tbthanhtoan.getRowCount();i++){
//    Tong += Integer.parseInt(tbthanhtoan.getValueAt(i,9).toString());
//    }
//    lbtongtien.setText(x.format(Tong)+" "+"VND");
//    }
  
    
    private void txttimkiemKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txttimkiemKeyReleased
        try{
            String query = "Select tbXe.MaHD,tbNhanVien.MaNV,TenNV,tbKhachhang.MaKH,TenKH,tbXe.MaXe,TenXe,ngaythue,ngaytra,GiaXe, convert(int,DATEDIFF(day,Ngaythue,Ngaytra))*GiaXe as \"Số ngày * giá xe\",trangthaihoadon \n" +
"from tbXe,tbNhanVien,tbHoaDon,tbkhachhang \n" +
"where tbNhanVien.MaNV=tbHoaDon.MaNV and tbHoaDon.MaKH=tbkhachhang.MaKH and tbXe.MaHD=tbHoaDon.MaHD and tbXe.MaHD = ? ";
            Connect a = new Connect();
            Connection conn = a.getConnection() ;
            PreparedStatement pst = conn.prepareStatement(query);
            pst.setString(1,txttimkiem.getText());
            ResultSet rs = pst.executeQuery();
            tbthanhtoan.setModel(DbUtils.resultSetToTableModel(rs));
              DecimalFormat x = new DecimalFormat("###,###,###");
//    int Tong = 0;
    double Tong = 0;
    for(int i=0;i<tbthanhtoan.getRowCount();i++){
//    Tong += Integer.parseInt(tbthanhtoan.getValueAt(i,9).toString());
     Tong += Integer.parseInt(tbthanhtoan.getValueAt(i,10).toString());
    }
    Tong = Tong + Tong*0.1;
    lbtongtien.setText(x.format(Tong)+" "+"VND");
            pst.close();

        }catch(Exception ex){
            ex.printStackTrace();
        }
        
    }//GEN-LAST:event_txttimkiemKeyReleased

    private void btnthanhtoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnthanhtoanActionPerformed
            try{
              DecimalFormat x = new DecimalFormat("###,###,###");
//    int Tong = 0;
    int Tong = 0;
    String trangthai1=" ";
    for(int i=0;i<tbthanhtoan.getRowCount();i++){
//    Tong += Integer.parseInt(tbthanhtoan.getValueAt(i,9).toString());
     Tong += Integer.parseInt(tbthanhtoan.getValueAt(i,10).toString());
     trangthai1=tbthanhtoan.getValueAt(0,11).toString();
    }
    Tong = (int) (Tong + Math.round(Tong*0.1));
              String Tong1 = String.valueOf(Tong);
            Connect a=new Connect();
            Connection conn=a.getConnection();
             if(JOptionPane.showConfirmDialog(this,"Bạn có muốn thanh toán","Xác nhận",JOptionPane.YES_NO_OPTION)==JOptionPane.YES_OPTION){
                 String trangthai = trangthai1;
                 
                if(trangthai.equals("Đã thanh toán")){
                JOptionPane.showMessageDialog(this,"Lỗi!Hóa đơn đã thanh toán rồi");
                }
                else{
            PreparedStatement ps =conn.prepareStatement("insert into tbHoaDonDaThanhToan values(?,?)");
            ps.setString(1,txttimkiem.getText());
            ps.setString(2,Tong1);
             PreparedStatement pd =conn.prepareStatement("update tbhoadon set trangthaihoadon=? where MaHD=?");
              pd.setString(1,"Đã thanh toán");
            pd.setString(2,txttimkiem.getText());
            pd.executeUpdate();
            int them=ps.executeUpdate();
            if(them>0){
                JOptionPane.showMessageDialog(this, "Thanh toán thành công");
                tbn.setRowCount(0);
                loadData();
            }else{
                
            }
                }
                 }
           
        }catch(Exception ex){
            System.out.println(ex.toString());
        }                      
    }//GEN-LAST:event_btnthanhtoanActionPerformed

    private void btnchitiethoadonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnchitiethoadonActionPerformed
          new chitiethoadonForm().setVisible(true); 
    }//GEN-LAST:event_btnchitiethoadonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnchitiethoadon;
    private javax.swing.JButton btnsua;
    private javax.swing.JButton btnthanhtoan;
    private javax.swing.JButton btnxoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JLabel lbtongtien;
    private javax.swing.JTable tbthanhtoan;
    private javax.swing.JTextField txttimkiem;
    // End of variables declaration//GEN-END:variables
}
