/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package quanlychothuexe;

import java.awt.Point;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.Statement;
import java.text.DecimalFormat;
import java.util.Date;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;
import quanlychothuexe.Connect;
/**
 *
 * @author ThanhTin
 */
public class ThongKeForm1 extends javax.swing.JPanel {

    /**
     * Creates new form ThongKeForm1
     */
    public ThongKeForm1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txttongdoanhthu = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        txtChonNam = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        radio1 = new javax.swing.JRadioButton();
        radio2 = new javax.swing.JRadioButton();
        radio4 = new javax.swing.JRadioButton();
        radio3 = new javax.swing.JRadioButton();
        btn_tim = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        cb_thang = new javax.swing.JComboBox<>();
        btn_timTheoThang = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 51));
        jLabel2.setText("TỔNG DOANH THU:");

        txttongdoanhthu.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txttongdoanhthu.setForeground(new java.awt.Color(255, 0, 51));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txttongdoanhthu, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txttongdoanhthu, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        txtChonNam.setText("nhập năm ");
        txtChonNam.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtChonNamMouseClicked(evt);
            }
        });
        txtChonNam.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtChonNamKeyReleased(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 21)); // NOI18N
        jLabel3.setText("Nhập năm:");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtChonNam)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtChonNam, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addContainerGap())
        );

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Hinh/Untitled-1.png"))); // NOI18N

        jPanel5.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        radio1.setText("Quý 1 ");

        radio2.setText("Quý 2");

        radio4.setText("Quý 4");

        radio3.setText("Quý 3");

        btn_tim.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btn_tim.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Hinh/Calendar.png"))); // NOI18N
        btn_tim.setText("Tìm theo quý");
        btn_tim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_timActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btn_tim, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(radio1)
                        .addGap(36, 36, 36)
                        .addComponent(radio2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(radio3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(radio4))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radio1)
                    .addComponent(radio2))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radio3)
                    .addComponent(radio4))
                .addGap(30, 30, 30)
                .addComponent(btn_tim, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel4.setText("Chọn tháng:");

        cb_thang.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));

        btn_timTheoThang.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btn_timTheoThang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Hinh/Date.png"))); // NOI18N
        btn_timTheoThang.setText("Tìm theo tháng");
        btn_timTheoThang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_timTheoThangActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(btn_timTheoThang, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cb_thang, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cb_thang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addComponent(btn_timTheoThang, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel6.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("Thống kê");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(176, 176, 176))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 790, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 469, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtChonNamKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtChonNamKeyReleased
        try{
            String query = "Select tbHoaDonDaThanhToan.*,ngaylaphd from tbHoaDonDaThanhToan,tbHoaDon where tbHoaDonDaThanhToan.MaHD = tbHoaDon.MaHD and year(NgayLapHD)=?";
            Connect a=new Connect();
            Connection conn = a.getConnection() ;
            PreparedStatement pst = conn.prepareStatement(query);
            pst.setString(1,txtChonNam.getText());
            ResultSet rs = pst.executeQuery();
            jTable1.setModel(DbUtils.resultSetToTableModel(rs));
            pst.close();

        }catch(Exception ex){
            ex.printStackTrace();
        }
    }//GEN-LAST:event_txtChonNamKeyReleased

    private void btn_timTheoThangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_timTheoThangActionPerformed
        if(cb_thang.getSelectedIndex()==0){
            try{
                String query = "Select tbHoaDonDaThanhToan.*,ngaylaphd from tbHoaDonDaThanhToan,tbHoaDon where tbHoaDonDaThanhToan.MaHD = tbHoaDon.MaHD and month(NgayLapHD)=1 AND year(NgayLapHD)=?";
                Connect a = new Connect();
                Connection conn = a.getConnection() ;
                PreparedStatement pst = conn.prepareStatement(query);
                pst.setString(1,txtChonNam.getText());
                ResultSet rs = pst.executeQuery();
                jTable1.setModel(DbUtils.resultSetToTableModel(rs));
                pst.close();
                Tong();
            }catch(Exception ex){
                System.out.println(ex.toString());
            }
        }
        if(cb_thang.getSelectedIndex()==1){
            try{
                String query = "Select tbHoaDonDaThanhToan.*,ngaylaphd from tbHoaDonDaThanhToan,tbHoaDon where tbHoaDonDaThanhToan.MaHD = tbHoaDon.MaHD and month(NgayLapHD)=2 AND year(NgayLapHD)=?";
                Connect a = new Connect();
                Connection conn = a.getConnection() ;
                PreparedStatement pst = conn.prepareStatement(query);
                pst.setString(1,txtChonNam.getText());
                ResultSet rs = pst.executeQuery();
                jTable1.setModel(DbUtils.resultSetToTableModel(rs));
                pst.close();
                Tong();
            }catch(Exception ex){
                System.out.println(ex.toString());
            }
        }
        if(cb_thang.getSelectedIndex()==2){
            try{
                String query = "Select tbHoaDonDaThanhToan.*,ngaylaphd from tbHoaDonDaThanhToan,tbHoaDon where tbHoaDonDaThanhToan.MaHD = tbHoaDon.MaHD and month(NgayLapHD)=3 AND year(NgayLapHD)=?";
                Connect a = new Connect();
                Connection conn = a.getConnection() ;
                PreparedStatement pst = conn.prepareStatement(query);
                pst.setString(1,txtChonNam.getText());
                ResultSet rs = pst.executeQuery();
                jTable1.setModel(DbUtils.resultSetToTableModel(rs));
                pst.close();
                Tong();
            }catch(Exception ex){
                System.out.println(ex.toString());
            }
        }
        if(cb_thang.getSelectedIndex()==3){
            try{
                String query = "Select tbHoaDonDaThanhToan.*,ngaylaphd from tbHoaDonDaThanhToan,tbHoaDon where tbHoaDonDaThanhToan.MaHD = tbHoaDon.MaHD and month(NgayLapHD)=4 AND year(NgayLapHD)=?";
                Connect a = new Connect();
                Connection conn = a.getConnection() ;
                PreparedStatement pst = conn.prepareStatement(query);
                pst.setString(1,txtChonNam.getText());
                ResultSet rs = pst.executeQuery();
                jTable1.setModel(DbUtils.resultSetToTableModel(rs));
                pst.close();
                Tong();
            }catch(Exception ex){
                System.out.println(ex.toString());
            }
        }
        if(cb_thang.getSelectedIndex()==4){
            try{
                String query = "Select tbHoaDonDaThanhToan.*,ngaylaphd from tbHoaDonDaThanhToan,tbHoaDon where tbHoaDonDaThanhToan.MaHD = tbHoaDon.MaHD and month(NgayLapHD)=5 AND year(NgayLapHD)=?";
                Connect a = new Connect();
                Connection conn = a.getConnection() ;
                PreparedStatement pst = conn.prepareStatement(query);
                pst.setString(1,txtChonNam.getText());
                ResultSet rs = pst.executeQuery();
                jTable1.setModel(DbUtils.resultSetToTableModel(rs));
                pst.close();
                Tong();
            }catch(Exception ex){
                System.out.println(ex.toString());
            }
        }
        if(cb_thang.getSelectedIndex()==5){
            try{
                String query = "Select tbHoaDonDaThanhToan.*,ngaylaphd from tbHoaDonDaThanhToan,tbHoaDon where tbHoaDonDaThanhToan.MaHD = tbHoaDon.MaHD and month(NgayLapHD)=6 AND year(NgayLapHD)=?";
                Connect a = new Connect();
                Connection conn = a.getConnection() ;
                PreparedStatement pst = conn.prepareStatement(query);
                pst.setString(1,txtChonNam.getText());
                ResultSet rs = pst.executeQuery();
                jTable1.setModel(DbUtils.resultSetToTableModel(rs));
                pst.close();
                Tong();
            }catch(Exception ex){
                System.out.println(ex.toString());
            }
        }
        if(cb_thang.getSelectedIndex()==6){
            try{
                String query = "Select tbHoaDonDaThanhToan.*,ngaylaphd from tbHoaDonDaThanhToan,tbHoaDon where tbHoaDonDaThanhToan.MaHD = tbHoaDon.MaHD and month(NgayLapHD)=7 AND year(NgayLapHD)=?";
                Connect a = new Connect();
                Connection conn = a.getConnection() ;
                PreparedStatement pst = conn.prepareStatement(query);
                pst.setString(1,txtChonNam.getText());
                ResultSet rs = pst.executeQuery();
                jTable1.setModel(DbUtils.resultSetToTableModel(rs));
                pst.close();
                Tong();
            }catch(Exception ex){
                System.out.println(ex.toString());
            }
        }
        if(cb_thang.getSelectedIndex()==7){
            try{
                String query = "Select tbHoaDonDaThanhToan.*,ngaylaphd from tbHoaDonDaThanhToan,tbHoaDon where tbHoaDonDaThanhToan.MaHD = tbHoaDon.MaHD and month(NgayLapHD)=8 AND year(NgayLapHD)=?";
                Connect a = new Connect();
                Connection conn = a.getConnection() ;
                PreparedStatement pst = conn.prepareStatement(query);
                pst.setString(1,txtChonNam.getText());
                ResultSet rs = pst.executeQuery();
                jTable1.setModel(DbUtils.resultSetToTableModel(rs));
                pst.close();
                Tong();
            }catch(Exception ex){
                System.out.println(ex.toString());
            }
        }
        if(cb_thang.getSelectedIndex()==8){
            try{
                String query = "Select tbHoaDonDaThanhToan.*,ngaylaphd from tbHoaDonDaThanhToan,tbHoaDon where tbHoaDonDaThanhToan.MaHD = tbHoaDon.MaHD and month(NgayLapHD)=9 AND year(NgayLapHD)=?";
                Connect a = new Connect();
                Connection conn = a.getConnection() ;
                PreparedStatement pst = conn.prepareStatement(query);
                pst.setString(1,txtChonNam.getText());
                ResultSet rs = pst.executeQuery();
                jTable1.setModel(DbUtils.resultSetToTableModel(rs));
                pst.close();
                Tong();
            }catch(Exception ex){
                System.out.println(ex.toString());
            }
        }
        if(cb_thang.getSelectedIndex()==9){
            try{
                String query = "Select tbHoaDonDaThanhToan.*,ngaylaphd from tbHoaDonDaThanhToan,tbHoaDon where tbHoaDonDaThanhToan.MaHD = tbHoaDon.MaHD and month(NgayLapHD)=10 AND year(NgayLapHD)=?";
                Connect a = new Connect();
                Connection conn = a.getConnection() ;
                PreparedStatement pst = conn.prepareStatement(query);
                pst.setString(1,txtChonNam.getText());
                ResultSet rs = pst.executeQuery();
                jTable1.setModel(DbUtils.resultSetToTableModel(rs));
                pst.close();
                Tong();
            }catch(Exception ex){
                System.out.println(ex.toString());
            }
        }
        if(cb_thang.getSelectedIndex()==10){
            try{
                String query = "Select tbHoaDonDaThanhToan.*,ngaylaphd from tbHoaDonDaThanhToan,tbHoaDon where tbHoaDonDaThanhToan.MaHD = tbHoaDon.MaHD and month(NgayLapHD)=11 AND year(NgayLapHD)=?";
                Connect a = new Connect();
                Connection conn = a.getConnection() ;
                PreparedStatement pst = conn.prepareStatement(query);
                pst.setString(1,txtChonNam.getText());
                ResultSet rs = pst.executeQuery();
                jTable1.setModel(DbUtils.resultSetToTableModel(rs));
                pst.close();
                Tong();
            }catch(Exception ex){
                System.out.println(ex.toString());
            }
        }
        if(cb_thang.getSelectedIndex()==11){
            try{
                String query = "Select tbHoaDonDaThanhToan.*,ngaylaphd from tbHoaDonDaThanhToan,tbHoaDon where tbHoaDonDaThanhToan.MaHD = tbHoaDon.MaHD and month(NgayLapHD)=12 AND year(NgayLapHD)=?";
                Connect a = new Connect();
                Connection conn = a.getConnection() ;
                PreparedStatement pst = conn.prepareStatement(query);
                pst.setString(1,txtChonNam.getText());
                ResultSet rs = pst.executeQuery();
                jTable1.setModel(DbUtils.resultSetToTableModel(rs));
                pst.close();
                Tong();
            }catch(Exception ex){
                System.out.println(ex.toString());
            }
        }
    }//GEN-LAST:event_btn_timTheoThangActionPerformed

    private void btn_timActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_timActionPerformed
        if(radio1.isSelected()){

            try{

                String query = "Select tbHoaDonDaThanhToan.*,ngaylaphd from tbHoaDonDaThanhToan,tbHoaDon where tbHoaDonDaThanhToan.MaHD = tbHoaDon.MaHD and(DATEPART(qq,NgayLapHD) IN (1)) AND year(NgayLapHD)=?";
                Connect a = new Connect();
                Connection conn = a.getConnection() ;
                PreparedStatement pst = conn.prepareStatement(query);
                pst.setString(1,txtChonNam.getText());
                ResultSet rs = pst.executeQuery();
                jTable1.setModel(DbUtils.resultSetToTableModel(rs));
                pst.close();
                Tong();

            }catch(Exception ex){
                System.out.println(ex.toString());
            }

        }
        else if(radio2.isSelected()){

            try{

                String query = "Select tbHoaDonDaThanhToan.*,ngaylaphd from tbHoaDonDaThanhToan,tbHoaDon where tbHoaDonDaThanhToan.MaHD = tbHoaDon.MaHD and(DATEPART(qq,NgayLapHD) IN (2)) AND year(NgayLapHD)=?";
                Connect a = new Connect();
                Connection conn = a.getConnection() ;
                PreparedStatement pst = conn.prepareStatement(query);
                pst.setString(1,txtChonNam.getText());
                ResultSet rs = pst.executeQuery();
                jTable1.setModel(DbUtils.resultSetToTableModel(rs));
                pst.close();
                Tong();
            }catch(Exception ex){
                System.out.println(ex.toString());
            }
        }
        else if(radio3.isSelected()){

            try{

                String query = "Select tbHoaDonDaThanhToan.*,ngaylaphd from tbHoaDonDaThanhToan,tbHoaDon where tbHoaDonDaThanhToan.MaHD = tbHoaDon.MaHD and(DATEPART(qq,NgayLapHD) IN (3)) AND year(NgayLapHD)=?";
                Connect a = new Connect();
                Connection conn = a.getConnection() ;
                PreparedStatement pst = conn.prepareStatement(query);
                pst.setString(1,txtChonNam.getText());
                ResultSet rs = pst.executeQuery();
                jTable1.setModel(DbUtils.resultSetToTableModel(rs));
                pst.close();
                Tong();
            }catch(Exception ex){
                System.out.println(ex.toString());
            }
        }
        else if(radio4.isSelected()){

            try{

                String query = "Select tbHoaDonDaThanhToan.*,ngaylaphd from tbHoaDonDaThanhToan,tbHoaDon where tbHoaDonDaThanhToan.MaHD = tbHoaDon.MaHD and(DATEPART(qq,NgayLapHD) IN (4)) AND year(NgayLapHD)=?";
                Connect a = new Connect();
                Connection conn = a.getConnection() ;
                PreparedStatement pst = conn.prepareStatement(query);
                pst.setString(1,txtChonNam.getText());
                ResultSet rs = pst.executeQuery();
                jTable1.setModel(DbUtils.resultSetToTableModel(rs));
                pst.close();
                Tong();
            }catch(Exception ex){
                System.out.println(ex.toString());
            }
        }

    }//GEN-LAST:event_btn_timActionPerformed

    private void txtChonNamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtChonNamMouseClicked
       txtChonNam.setText("");
    }//GEN-LAST:event_txtChonNamMouseClicked
private void Tong() {
        DecimalFormat x = new DecimalFormat("###,###,###");
        int Tong = 0;
       for(int i=0;i<jTable1.getRowCount();i++){
           Tong += Integer.parseInt(jTable1.getValueAt(i,1).toString());
       }
    
            txttongdoanhthu.setText(x.format(Tong)+" "+"VNĐ");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_tim;
    private javax.swing.JButton btn_timTheoThang;
    private javax.swing.JComboBox<String> cb_thang;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JRadioButton radio1;
    private javax.swing.JRadioButton radio2;
    private javax.swing.JRadioButton radio3;
    private javax.swing.JRadioButton radio4;
    private javax.swing.JTextField txtChonNam;
    private javax.swing.JLabel txttongdoanhthu;
    // End of variables declaration//GEN-END:variables

}
